on:
  workflow_call:
    inputs:
      coverage_artifact:
        required: false
        type: string
      args:
        required: false
        type: string
    secrets:
      sonar_token:
        required: true
      sonar_project_key:
        required: true
      sonar_organization:
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download coverage artifact
        if: ${{ inputs.coverage_artifact != '' }}
        uses: actions/download-artifact@v4.3.0
        with:
          name: ${{ inputs.coverage_artifact }}

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectKey: ${{ secrets.sonar_project_key }}
          organization: ${{ secrets.sonar_organization }}
          args: ${{ inputs.args }}
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
